name: Code Coverage

on:
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'fix/**'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-levels: 36
          target: default

      - name: Check Android SDK path
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          ls $ANDROID_HOME/platforms || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests with coverage
        run: ./gradlew koverXmlReport koverHtmlReport --stacktrace

      - name: Upload test report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest
          retention-days: 7

      - name: Add coverage report to PR
        uses: mi-kas/kover-report@v1.9
        with:
          path: ${{ github.workspace }}/app/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "📊 Code coverage report"
          update-comment: true
          min-coverage-overall: 40
          coverage-counter-type: LINE

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: app/build/reports/kover/html
          retention-days: 7
